/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangScrittiSlugRouteImport } from './routes/$lang.scritti.$slug'
import { Route as LangTemaTemaRouteImport } from './routes/$lang.tema.$tema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangScrittiSlugRoute = LangScrittiSlugRouteImport.update({
  id: '/scritti/$slug',
  path: '/scritti/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangTemaTemaRoute = LangTemaTemaRouteImport.update({
  id: '/tema/$tema',
  path: '/tema/$tema',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/scritti/$slug': typeof LangScrittiSlugRoute
  '/$lang/tema/$tema': typeof LangTemaTemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/scritti/$slug': typeof LangScrittiSlugRoute
  '/$lang/tema/$tema': typeof LangTemaTemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/scritti/$slug': typeof LangScrittiSlugRoute
  '/$lang/tema/$tema': typeof LangTemaTemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$lang' | '/$lang/' | '/$lang/scritti/$slug' | '/$lang/tema/$tema'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang' | '/$lang/scritti/$slug' | '/$lang/tema/$tema'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/scritti/$slug'
    | '/$lang/tema/$tema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/scritti/$slug': {
      id: '/$lang/scritti/$slug'
      path: '/scritti/$slug'
      fullPath: '/$lang/scritti/$slug'
      preLoaderRoute: typeof LangScrittiSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/tema/$tema': {
      id: '/$lang/tema/$tema'
      path: '/tema/$tema'
      fullPath: '/$lang/tema/$tema'
      preLoaderRoute: typeof LangTemaTemaRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangScrittiSlugRoute: typeof LangScrittiSlugRoute
  LangTemaTemaRoute: typeof LangTemaTemaRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangScrittiSlugRoute: LangScrittiSlugRoute,
  LangTemaTemaRoute: LangTemaTemaRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
